### ISSUE TITLE
Error message from Google when trying to run the code

### ISSUE THREAD

**Issue by SabrinaBeeCom** [HR/google-drive-unshare#2]
When I want to authenticate with my Google account, there is a security message showing up saying that this app is not verified by Google. So I can't run the function. Can you please help? Thank you in advance :-)

**Comment by HR** [comment]
You need to allow it to be run anyway

![permission](https://github.com/HR/google-drive-unshare/raw/master/.github/permissions.png?raw=true)

![permission](https://github.com/HR/google-drive-unshare/raw/master/.github/permissions_allow.png?raw=true)
