### ISSUE TITLE
User does not exist

### ISSUE THREAD

**Issue by icionaime** [HR/google-drive-unshare#4]
Hi there,
Thanks a lot for the script. When running it I keep getting the error 'User does not exist' even if I am copy/pasting the owner email I want to remove from my folders: https://share.getcloudapp.com/qGulvydb
Any idea how to fix this?
Thanks!

**Comment by HR** [comment]
> Hi there,
> Thanks a lot for the script. When running it I keep getting the error 'User does not exist' even if I am copy/pasting the owner email I want to remove from my folders: https://share.getcloudapp.com/qGulvydb
> Any idea how to fix this?
> Thanks!

Can you share the logs? (Under `View > Logs` or `View > Stackdriver logs`)

Also did you specify his email in the code in the correct format i.e. `var userEmail = 'owner@gmail.com'`

**Comment by icionaime** [comment]
Sure, sorry it's in french but it basically says 'Exception : User does not exist' : https://share.getcloudapp.com/GGu2rLqA

**Comment by HR** [comment]
> Sure, sorry it's in french but it basically says 'Exception : User does not exist' : https://share.getcloudapp.com/GGu2rLqA

It would be very helpful if you could find the line in the code where the error occurred (should be somewhere in the logs).

Also, did you set `copyNotOwned` to `true`?

If he is the owner then you cannot unshare the files with him instead you have to either make yourself the owner first (if he has allowed that in the settings) or make a copy of the items in Google Drive. To just do that, comment/remove lines 15-23 https://github.com/HR/google-drive-unshare/blob/master/Code.gs#L15-L23
